name: website
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.40.0
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/header.jpeg
    - assets/Fire.png
    - assets/helldivers2.jpeg
    - assets/finals.jpg
    - assets/rl.jpg
    - assets/bg.jpeg
